### ISSUE TITLE
MPU6050中央焊盘是否应该接地？

### ISSUE THREAD

**Issue by fan-ziqi** [peng-zhihui/HoloCubic#52]
稚晖君您好，我发现您的PCB中MPU6050中央焊盘为GND网络且打了过孔，但MPU6050数据手册中说明
“The MPU-60X0 has very low active and standby current consumption. The exposed die pad is not required for heat sinking, and should not be soldered to the PCB. Failure to adhere to this rule can induce performance changes due to package thermo-mechanical stress. There is no electrical connection between the pad and the CMOS.”
MPU-60X0有很低的动态性能和标准的电流损耗。该焊盘不要求进行散热，同时也不能连接到PCB上。该焊盘是为了增加芯片的机械应力，不应该有任何的电气连接。“
请问您将中央焊盘接地是什么原因，接地会不会对MPU6050造成影响？如果手册中说不接地应该怎么处理呢？

**Comment by peng-zhihui** [comment]
是的，这个是我之前没注意，但是实测没太大影响，你可以自己把pcb相关连线去掉一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 范子琦 ***@***.***&gt;
发送时间: 2021年5月23日 17:29
收件人: peng-zhihui/HoloCubic ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/HoloCubic] MPU6050中央焊盘是否应该接地？ (#52)





 
稚晖君您好，我发现您的PCB中MPU6050中央焊盘为GND网络且打了过孔，但MPU6050数据手册中说明
 “The MPU-60X0 has very low active and standby current consumption. The exposed die pad is not required for heat sinking, and should not be soldered to the PCB. Failure to adhere to this rule can induce performance changes due to package thermo-mechanical stress. There is no electrical connection between the pad and the CMOS.”
 MPU-60X0有很低的动态性能和标准的电流损耗。该焊盘不要求进行散热，同时也不能连接到PCB上。该焊盘是为了增加芯片的机械应力，不应该有任何的电气连接。“
 请问您将中央焊盘接地是什么原因，接地会不会对MPU6050造成影响？如果手册中说不接地应该怎么处理呢？

**Comment by fan-ziqi** [comment]
> 是的，这个是我之前没注意，但是实测没太大影响，你可以自己把pcb相关连线去掉一下。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 范子琦 ***@***.***&gt; 发送时间: 2021年5月23日 17:29 收件人: peng-zhihui/HoloCubic ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[peng-zhihui/HoloCubic] MPU6050中央焊盘是否应该接地？ (#52) 稚晖君您好，我发现您的PCB中MPU6050中央焊盘为GND网络且打了过孔，但MPU6050数据手册中说明 “The MPU-60X0 has very low active and standby current consumption. The exposed die pad is not required for heat sinking, and should not be soldered to the PCB. Failure to adhere to this rule can induce performance changes due to package thermo-mechanical stress. There is no electrical connection between the pad and the CMOS.” MPU-60X0有很低的动态性能和标准的电流损耗。该焊盘不要求进行散热，同时也不能连接到PCB上。该焊盘是为了增加芯片的机械应力，不应该有任何的电气连接。“ 请问您将中央焊盘接地是什么原因，接地会不会对MPU6050造成影响？如果手册中说不接地应该怎么处理呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

多谢大佬回复~这就去打一版试一下

**Comment by fan-ziqi** [comment]
多谢大佬回复~这就去打一版试一下

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月23日 19:38:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [peng-zhihui/HoloCubic] MPU6050中央焊盘是否应该接地？ (#52)




 是的，这个是我之前没注意，但是实测没太大影响，你可以自己把pcb相关连线去掉一下。 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 范子琦 ***@***.***&amp;gt; 
 发送时间: 2021年5月23日 17:29 
 收件人: peng-zhihui/HoloCubic ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: 回复：[peng-zhihui/HoloCubic] MPU6050中央焊盘是否应该接地？ (#52) 
 
 
 
 
 
   
 稚晖君您好，我发现您的PCB中MPU6050中央焊盘为GND网络且打了过孔，但MPU6050数据手册中说明 
  “The MPU-60X0 has very low active and standby current consumption. The exposed die pad is not required for heat sinking, and should not be soldered to the PCB. Failure to adhere to this rule can induce performance changes due to package thermo-mechanical stress. There is no electrical connection between the pad and the CMOS.” 
  MPU-60X0有很低的动态性能和标准的电流损耗。该焊盘不要求进行散热，同时也不能连接到PCB上。该焊盘是为了增加芯片的机械应力，不应该有任何的电气连接。“ 
  请问您将中央焊盘接地是什么原因，接地会不会对MPU6050造成影响？如果手册中说不接地应该怎么处理呢？ 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by franva** [comment]
@fan-ziqi  @peng-zhihui  硬件方面小白问一个问题。

请问去哪里打板子呢？ 能不能给个链接？ 多谢啦～！

**Comment by peng-zhihui** [comment]
> @fan-ziqi @peng-zhihui 硬件方面小白问一个问题。
> 
> 请问去哪里打板子呢？ 能不能给个链接？ 多谢啦～！

嘉立创

**Comment by fan-ziqi** [comment]
嘉立创 捷配 猎板

在 2021年7月17日星期六，Winston Fan ***@***.***> 写道：
